name: Draft release

on:
  workflow_dispatch:

permissions:
  contents: write # For creating releases.
  discussions: write #  For creating a discussion.

jobs:
  package-rpm:
    runs-on: ubuntu-latest
    container: "centos:8"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
          go-version: 1.18
      
      - name: Install nfpm and envsubst
        run: |
          mkdir -p ~/.local/bin
          curl -sSfL https://github.com/goreleaser/nfpm/releases/download/v2.22.2/nfpm_2.22.2_`uname -s`_`uname -m`.tar.gz | tar -C ~/.local/bin -zxv nfpm
          curl -sSfL https://github.com/a8m/envsubst/releases/download/v1.1.0/envsubst-`uname -s`-`uname -m` -o envsubst
          chmod +x envsubst
          mv envsubst ~/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PAT

      - run: mkdir release-packages
      
      - name: build amd64
        env:
          VERSION: ${{ vars.VERSION }}
          BINARY: ${{ vars.BINARY }}
          GO111MODULE: on
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=1 CGO_LDFLAGS="-static" go build -ldflags "-X main.version=${VERSION}" -o build/${BINARY}
          
      - name: package amd64
        run: |
          nfpm pkg -f ./linux/nfpm.yaml --target "release-packages/${BINARY}-${VERSION}-amd64.rpm"

      - name: build arm64
        env:
          VERSION: ${{ vars.VERSION }}
          BINARY: ${{ vars.BINARY }}
          GO111MODULE: on
        run: |
          GOOS=linux GOARCH=arm64 CGO_ENABLED=1 CGO_LDFLAGS="-static" go build -ldflags "-X main.version=${VERSION}" -o build/${BINARY}
      
      - name: package arm64
        run: |
          nfpm pkg -f ./linux/nfpm.yaml --target "release-packages/${BINARY}-${VERSION}-amd64.rpm"

      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          discussion_category_name: "📣 Announcements"
          files: ./release-packages/*
      
